In [1]:
# Importing libraries
from ctgan import CTGAN
import pandas as pd

In [8]:
# Loading real dataset after preprocessing
df = pd.read_csv("../Datasets/creditcard_preprocessed.csv")

In [9]:
# Using GenAI Model for Oversampling of Class = 1(fraud)
ctgan = CTGAN(epochs=50, batch_size=100, verbose=True)
ctgan.fit(df, discrete_columns=['Class'])

Gen. (-0.10) | Discrim. (-0.66): 100%|███████████████████████████████████████████████████████████| 50/50 [2:58:39<00:00, 214.40s/it]

In [31]:
synthetic_data = ctgan.sample(5000)

In [32]:
synthetic_data['Class'] = 1

In [34]:
synthetic_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-0.592490,1.261063,0.542455,1.464406,2.593297,-1.077141,-0.560853,-0.796953,2.004644,-0.019487,...,-0.166583,0.055700,0.126099,-0.709987,-0.163384,0.732528,0.083118,0.001944,-0.166015,1
1,0.677403,-0.818511,-0.299763,0.631170,-1.284627,-1.865711,-0.282948,-0.559617,1.359273,1.246591,...,0.271397,-1.221129,0.124480,-0.010416,-0.854741,0.072481,0.060709,0.050122,0.563171,1
2,-0.550191,2.008249,0.827323,2.252646,-1.269430,0.852633,-0.226924,-0.818994,-0.637753,-0.950515,...,-0.102596,0.902552,-0.322641,-0.060485,-0.285592,0.223319,-0.123185,-0.021882,-0.098784,1
3,-1.201370,-16.474169,10.722600,-8.814064,1.233338,-12.131948,-2.289939,-13.771982,5.299766,-8.012049,...,-5.461466,-1.656520,0.257784,-0.103364,-0.294505,-0.026473,-1.039370,0.162082,-0.376710,1
4,0.603358,1.746640,0.273348,-1.775997,-0.183455,-0.486876,-0.696286,0.064525,-0.236826,-0.350440,...,0.350900,-0.712301,-0.110455,-0.019931,0.145988,0.001367,-0.062454,-0.021193,-0.369766,1

In [35]:
# Saving the synthetic data
synthetic_data.to_csv('../Datasets/creditcard_synthetic.csv', index=False)

In [36]:
# Combine original and synthetic data
augmented_df = pd.concat([df, synthetic_data], ignore_index=True)

# Shuffle the dataset for randomness
augmented_df = augmented_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Save augmented dataset
augmented_df.to_csv('../Datasets/creditcard_augmented.csv', index=False)

In [37]:
augmented_df.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-0.967461,-1.214111,0.573411,2.907422,1.355873,-1.174616,1.573442,0.830477,-0.344487,1.003815,...,-0.062443,0.708791,-0.280562,0.145173,0.135885,-0.162246,-0.634738,-0.438097,0.340199,0
1,0.870180,-4.374494,1.720756,-0.283283,-1.419023,-0.540330,-0.235455,0.141986,-0.178588,2.659507,...,-0.446591,-0.419491,0.391924,-0.456796,0.034762,-0.455549,-1.786650,-0.330895,-0.297776,0
2,-1.264715,1.097677,-0.164882,0.176646,0.734756,0.025320,0.673811,-0.336997,0.344617,0.283078,...,-0.176758,-0.728021,-0.041762,-1.246892,0.267670,-0.537954,0.025471,0.014927,-0.109346,0
3,1.545591,2.160707,0.011426,-2.483200,-0.280012,0.914775,-0.945271,0.646703,-0.372235,0.119328,...,0.124816,0.446405,-0.171981,-0.996681,0.521044,0.286452,-0.095692,-0.100791,-0.338436,0
4,-1.407593,1.272196,0.472315,-1.107531,0.793957,1.039064,0.504867,-0.006639,0.235595,-0.010333,...,-0.119193,-0.335503,-0.302328,-1.884768,0.768501,-0.202959,0.035910,0.023181,-0.349231,0
5,1.026724,-0.566187,1.081028,-0.441786,0.922245,1.427920,-0.075185,1.327386,-0.285144,-1.575931,...,0.073443,0.398685,-0.660990,0.399734,0.845085,1.246002,-0.043151,0.020416,-0.012393,0
6,1.563828,-1.060795,-0.906702,0.960105,0.057893,0.261361,-0.726221,0.521894,-0.079857,0.207756,...,0.575795,1.213542,0.587620,0.013183,-0.675182,-0.304183,0.165583,0.270642,0.547539,0
7,1.484902,0.094869,1.291059,-0.902011,-0.272609,1.036317,-1.452685,1.038731,-0.135960,-0.321027,...,0.220449,0.684604,-0.321277,-0.166630,-0.073230,-0.198049,0.085460,0.092155,-0.349231,0
8,-1.023475,0.924651,-0.451692,0.893315,0.679742,-1.050524,-0.588073,-0.225491,-0.111101,0.367800,...,0.097697,-0.013429,-0.081723,0.450152,0.120103,0.372449,-0.030827,0.054904,0.284985,0
9,0.409495,1.812764,-0.356520,-0.459360,1.442413,-0.431486,-0.119285,-0.344864,0.046468,0.764784,...,0.328955,1.144268,-0.039136,0.047574,0.161777,-0.412495,0.039217,-0.043186,-0.137573,0

In [38]:
augmented_df['Class'].value_counts()

Class
0    284315
1      5492
Name: count, dtype: int64

So now the synthetic fraud class data has been added to the preprocessed dataset to form new datset.